### ISSUE TITLE
51% attack possibility with negative voting

### ISSUE THREAD

**Issue by vfat0** [andrecronje/solidly#45]
The current voting version allows for a 51% attack on the system by a coalition of NFT holders: amass 51% of the vote, use 49% to negate all opposition votes, use the remaining 2% to direct all emissions.

Assuming the purpose of negative votes is to be able to cancel out fake pools (a bad actor uses their NFT to create a pool with 2 tokens they only own themselves), this also seems to be difficult to achieve with the current version: Who would want to use up their votes to cancel someone else rather than to vote for themselves? It would only work with perfect coordination between the teams (everyone agrees to downvote the bad actor according to their share of the total supply). Coordination between 24 teams seems unworkable.

I'd like to propose the following change to resolve these two points:
-Each NFT has 2 vote tallies, positive and negative (so if you have 10k veSOLID you can vote 10k up and 10k down)
-Negative votes do not affect emissions, but
-If a gauge has negative votes equal to e.g. 80% of the total vote, anyone can kick that gauge, removing it from emissions

Of course this still allows for a 80% attack but it seems that such an attack would be against the attackers' best interest as it could kill confidence in the project and correspondingly the value of their investment.

I would also like to propose a reduction in the new pool listing fee from 0.5% of circulating supply to 0.1%, it seems to me that 0.5% is too high for small projects and so would greatly diminish innovation.

Comments are most welcome, if there is support behind this I can submit it as a pull request.

**Comment by andrecronje** [comment]
A 51% attack ignores game theory. A coalition that controls 51% that negates other entrants, means no reason to purchase SOLID, which means the coalition will destroy the very value they try to control. While it is technically possible, its highly improbable, since the coalition will not only destroy their own value accrual, but also alienate themselves, quickly leading to a fork. This also assumes it is possible to control 51%, which we have seen from most open ended protocols, is unlikely.

Assuming someone does attempt a fake pool, it is likely for majority holders to direct some of their veNFT voting rights to vote out the bad actor, since again, it sets precedence, if they don't, more will simply follow the same strategy, eventually destroying the value accrual. It is in their own best interest to vote out bad actors.

Coordination between veNFT's is not required, simply a few need to direct some of their voting power to stop aggressors. Your proposal assumes everyone behaves in the absolute possible worst manner even at the detriment of their own vests.

--

Too the second part, I agree the 0.5% is too high and would remove small entrants, I have modified this in two ways;

- whitelisting is on tokens, no longer gauges
- veNFT holders with a position > listing fee can whitelist new tokens

This should address those concerns.

**Comment by westonnelson** [comment]
Great points...two thoughts on feedback: New pool listing fee of .1% seems entirely reasonable and in the best interest of attracting new protocols/innovation as mentioned. 

Bigger concern is that essentially I'm hearing a fear of collusion most clearly here. Would think it is wise to investigate this more thoroughly because you objectively are correct this is possible although unlikely. 

-Wouldn't it be possible to use a Keeper Infra to monitor this/prevent as all addresses in possession will always be easily tracked? Ie; code in restrictions that no more than x number of protocols may vote in unison. Or, if this is done and identified, trigger an alert for governance to review for foul play.

-This seems to warrant imminent discussion by the community at large due to timing, will research implications of this more myself. 

Thank you for identifying this.

**Comment by vfat0** [comment]
I completely agree that a 51% attack doesn't make sense but have reason to believe it is very much being considered. I guess having an open discussion about why it would defeat the object and only lead to a fork, wasting everyone's time and all users' confidence in the project, may be enough of a deterrent for would-be attackers. Would be interested to hear a devil's advocate view on this, if there is one.

On the subject of countering fake pools I disagree about it not requiring co-ordination but it would probably only need to be between the 2-3 coalitions and so wouldn't be as difficult as I described in my original post. More importantly the fact that this option exists would deter people from attempting to do fake pools in the first place.

Appreciate the changes to whitelisting, makes things much simpler indeed.

**Comment by andrecronje** [comment]
It's one of those things that sounds cool in theory "control the protocol", but in practice, you quickly realize doesn't make sense (unless you want to penalize yourself, owning 51% of the protocol you are planning on destroying is extreme even by my standards, and I love sending a good message). That being said, glad its being discussed. I considered available options;

1. Build on-chain mechanisms to prevent fake pools, this led me down the following rabbit hole;
- Require fees accrued (fake token holder can simply add trades)
- Require token to be transferable to voter (fake token can build in allowance for voter)
- Deploy new contract that transfers the tokens (fake token holder can fork mainnet, check contract address, and whitelist)
- Deploy new contract on every token accrual to transfer tokens (this one in theory could work, but heavily increases overall cost + complexity of the system)

The above thinking made me realize a penalty/slashing mechanism was required, this can be addressed via;

2. Adding a DAO (I want to avoid this at all costs)
3. Forcing veNFT participants to vote in new gauges (creates a convex-curve style net result)
4. Voting to slash veNFT positions (the finality of this is a bit extreme, and adds DAO layers)
5. Penalized voting

I ended up with penalized voting since it achieves the requirements with the least amount of coordination and code complexity, but this is based off of a few assumptions;

- a) Large holders won't create fake pools ~ the rational here is that it is detrimental to their own position
- b) Only small holders will create fake pools (1. because they are likely anon, and 2. because of assumption A)
- c) Large holders won't use the mechanism to vote out new entrants ~ since their value accrual is dependent on new entrants

Ofcourse, the above does assume majority rational actors, which I know crypto has proven isn't always true, but even in that case, hard forks are a viable option.

**Comment by westonnelson** [comment]
So here is a way to send a message and achieve the outcome desired...send a message with extreme penalized voting. Make the consequences severe, and this is deterred as I see it. 

And the risk of collusion (accepting your assumptions as true...which does seem reasonable)... this should be recitified then here to being almost probabilistically irrelevant, yes?

**Comment by 0xdoppl** [comment]
Even if one's party is rational, the irrationality and cooperation of the others isn't a guarantee. The strategy then might be to race toward a 51% majority, if only because the other party can't be prevented setting out to be irrational themselves. Not to mention there will be likely be a sweet spot to tread where an effective majority short of 51% will be maintained, reaping it's benefits while falling short enough of isolation and inciting a fork. I think then there is plenty rational incentive to adopt this strategy not to mention one stands only to gain from this greedy accumulative strategy up until the limit case you've pointed out. 

I think this should really be directly addressed, perhaps in next iterations, but i do think at least some minimal form of curve weighting the power of a votes themselves should be considered. For instance, for every interval of 1% accumulated votes in a pool, as it approaches say 50% the effect of the next vote is halved such that a 1% vote on a pool ~0% counts for 1% while that same 1% counts for 0.5% on a pool with 50%. That 1% vote will then result not in a 51% but rather 50.5%. 

Tuning a voting curve (wiki terms this quantitative voting) like this can incentivize distributing votes across pools with lower accumulated votes, as my vote goes further on pools that have less votes. The more votes accumulate for a pool the more incentivized all participants are not to vote for it. Once again, it can be tuned to have a kink so that this penalty is negligible, then more costly within a given range of an asymptote of say 51%.
